GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/blogs/6890d107d08cd9fe93b43a86

###
GET http://localhost:3003/api/info

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "War and Peace",
    "author": "Ernst Hemmingway",
    "url": "www.yahoo.com",
    "likes": 5
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "author": "Ernst Hemmingway",
    "url": "www.yahoo.com",
    "likes": 5
}

###
DELETE  http://localhost:3003/api/blogs/6890d107d08cd9fe93b43a86