GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/blogs/68964b4ca2aa8e438243a37b

###
GET http://localhost:3003/api/info

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "War and Peace",
    "author": "Ernst Hemmingway",
    "url": "www.yahoo.com",
    "likes": 5
}

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "author": "Ernst Hemmingway",
    "url": "www.yahoo.com",
    "likes": 5
}

###
PUT  http://localhost:3003/api/blogs/688527293caee9e748c4f2cc
content-type: application/json

{
    "likes": 6
}

###
DELETE  http://localhost:3003/api/blogs/68964b4ca2aa8e438243a37b