POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "PaulB",
  "password": "byte"
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "PaulB",
    "name": "Paul Blankenship",
    "password": "byte"
}