GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/4

###
GET http://localhost:3001/api/info

###
GET http://localhost:3001/api/persons/684b6a8c1492c1deffdd894b

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "fred flinstone",
    "number": "111-111-1111"
}

###
PUT  http://localhost:3001/api/persons/6874074f89fd3122244770b5 
content-type: application/json

{
    "name": "fred flinstone",
    "number": "222-222-2222"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "T2",
    "number": "111-1111111"
}

###
DELETE http://localhost:3001/api/persons/684b6a96b8d26b959a817748