GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/4

###
GET http://localhost:3001/api/info

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "fred flinstone",
    "number": "111-111-1111"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "T2",
    "number": "111-111-1111"
}

###
DELETE http://localhost:3001/api/persons/685b28cedc2870d06db7f700